language: node_js
node_js:
  - "node"
  - "6"
  - "6.0"
  - "5"
  - "5.0"
  - "4"
  - "4.0"
addons:
  code_climate:
    repo_token: 7a0207c7c0829fa719ced9a4099dc26cd4f63700434bd391e5ae598f39b0e0dd
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
